apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valeosense
resources:
- namespace.yaml
- storage.yaml
- config.yaml
- stores.yaml
- seed.yaml
- workloads.yaml
- network.yaml
configMapGenerator:
- name: clickhouse-memory
  files:
  - memory.xml
  options:
    labels:
      valeosense.io/phase: infra
